### ISSUE TITLE
New duo plus ads at the end of lessons

### ISSUE THREAD

**Issue by mxnemu** [blmage/duolingo-sound-controls#6]
Since this week on desktop duolingo auto plays video+audio ads about duoplus at the end of lessons on the last screen in the series where you get the score. 

These self promo ads ignore the sound settings of this addon.

Edit: the page uses a `<video>` tag. I might post the body html if I see it again, in case that helps. 

Btw, thank you for making this addon! :heart: It's super handy and I love not having to lower my entire browser's volume for duo all the time.

**Comment by blmage** [comment]
Thanks for your feedback, much appreciated!

The conditions for the video ad to be displayed seem rather restrictive (1 chance in 10 after having completed several sessions, if eligible for the A/B test), but in order to test it this can be worked around by pushing `{ type: "plusPromoInterstitial" }` to the list of post-session screens (a search on `plusPromoInterstitial` in the JS scripts should lead to the right spot for a breakpoint).

Anyway, since it's managed via a `<video>` tag, I feel like this is probably outside of the scope of the extension: the video player already features sound controls, and major browsers should mute it by default.

I'd be interested to know if any ad plays sounds without a visible player though, for example over an animation.

Closing this for now, but don't hesitate to comment again here if you come across such a case!
